---
title: Een bestand toevoegen in de Editor
hero_image: images/banner.png
description: Een bestand toevoegen in de Editor
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Een bestand toevoegen in de Editor
